name=input("Enter your name: ")
age =input("Enter your age: ")
marks=input("Enter your marks: ")
print("Welcome ",name)
print("Your age is: ",age)
print("Your marks is:",marks)
print("Your user name : ",name ,age)
a=input("Enter the value of a: ")
b=input("Enter the value of b: ")
print("Sum of","a+b is",a+b)
